apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic-microservices-app
  namespace: argocd  # Argo CD expects apps in this namespace
spec:
  project: default

  source:
    repoURL: https://github.com/Akerman0509/spring-petclinic-microservices
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: new-app-spring2

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
